POST http://127.0.0.1:8080/app/thing/register
Content-Type: application/json

{
  "name": "COVER 1",
  "id": "testA",
  "components": {
    "cover": {
      "name": "cover",
      "type": "int",
      "value": 1
    },
    "humidity": {
      "name": "humidity",
      "type": "int",
      "value": 1
    }
  }
}